Repository ErlichLiu/DeepClaude, pull requests merged in 2025-03, with the labels that each got.

#73 Added mounting of config file and add the none api-key verification to prevent none api-key from causing exceptions
  app/utils/auth.py
  docker-compose.yml
Labels: enhancement, good first issue

#81 readme增加服务器启动方式
  README.md
Labels: documentation

#78 Fix logger level setting
  app/main.py
  app/utils/logger.py
Labels: bug

#84 Fixed: mismatched file path mounting in docker-compose
  docker-compose.yml
Labels: bug

#104 Feat/allow proxy by model
  app/deepclaude/deepclaude.py
  app/manager/model_manager.py
  app/model_manager/model_configs.json
  app/openai_composite/openai_composite.py
  frontend/index.html
  frontend/js/config.js
Labels: enhancement
